services:
  bot:
    build: .
    #image: 192.168.0.108:5051/ism/patchbot:latest
    container_name: patchbot
    restart: unless-stopped
    env_file:
      - .env
    network_mode: host          
    environment:
      HTTP_PROXY:  "http://127.0.0.1:10808"
      HTTPS_PROXY: "http://127.0.0.1:10808"
      # опционально, если в коде читаешь:
      PROXY_URL:   "http://127.0.0.1:10808"
    volumes:
      - ./data:/app/data
